<img src = "images/logos.png" width = 600, align = "center">
<br>
<h1 align=center><font size = 5>Numpy in Python</font></h1>

## Numpy array 

En soi, un array  numpy est similaire à une liste, habituellement de taille fixe et contenant des valeurs **du même type**. Une liste peut être typée en array numpy assez facilement :

In [1]:
import numpy as np

Il suffit ensuite de la typer comme suit :

In [2]:
a=np.array([0,1,2,3, 4])
a

array([0, 1, 2, 3, 4])

La variable a est alors du type "numpy.ndarray":

In [3]:
type(a)

numpy.ndarray

L'accès aux valeurs se fait de la même manière que pour les listes :

In [4]:
print("a[0]:",a[0])
print("a[1]:",a[1])
print("a[2]:",a[2])
print("a[3]:",a[3])
print("a[4]:",a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


Comme un array numpy ne contient que des valeurs du même type, il possède un attribut permettant d'y accéder :


In [5]:
a.dtype

dtype('int32')

Dans le cas d'un array numpy contenant des réels : 

In [6]:
b=np.array([3.1,11.02,6.2, 213.2,5.2])

In [7]:
type(b)

numpy.ndarray

In [8]:
b.dtype

dtype('float64')

Les valeurs contenues dans un array numpy sont directement modifiables :

In [9]:
a[0]=100
a

array([100,   1,   2,   3,   4])

**Quelques attributs et méthodes spécifiques :**

In [10]:
a=np.array([0,1,2,3, 4])
a

array([0, 1, 2, 3, 4])

L'attibut **size** : 

In [11]:
a.size

5

Les attributs suivants prendront plus de sens lors du prochain notebook et en particulier lorsque l'array est de plus grande dimension.<br> L'attribut **“ndim”** represente la dimension de l'array : 

In [12]:
a.ndim

1

L'attribut **“shape”** est un tuple d'entiers retournant la taille (size) de chaque dimension :

In [13]:
a.shape #shape considère directement qu'on est en multidimentionnel (vecteur)= morceau de matrice. ici(5,1)le 1 ne s'écrit pas


(5,)

La méthode **mean** retourne la moyenne des valeurs de l'array : 

In [14]:
mean=a.mean()
mean #la moyenne est toujours considérée comme un float

2.0

La méthode **std()** retourne l'ecart-type des valeurs de l'array : 

In [15]:
ecart_type=a.std()#standart deviation
ecart_type #un écart type est la racine carée de la variance

1.4142135623730951

Les méthodes **max()** et **min()**

In [16]:
a.max()#attention max et min sont des fonction et non des attributs il faut mettre les parentheses a la fin

4

In [17]:
a.min()

0

## Opérations sur les arrays numpy

Considerons les arrays numpy 'u' et 'v':

In [18]:
u=np.array([1,0])
v=np.array([0,1])

Il est possible de les additionner et d'affecter le résultat à une troisième variable z :

In [19]:
z=u+v
z

array([1, 1])

####   Créer ci-dessous la soustraction u-v

In [20]:
u-v

array([ 1, -1])

 <div align="right">
<a href="#1" class="btn btn-default" data-toggle="collapse">Solution</a>

</div>
<div id="1" class="collapse">
```
u-v
```
</div>

Il est possible de multiplier tous les élément d'un array numpy par une même valeur (équivalent de la multiplication d'un vecteur par un scalaire) :

In [21]:
w=2*u
w

array([2, 0])

## Mulipication entre arrays numpy

 Considrons les arrays numpy 'u' et 'v':

In [22]:
u=np.array([1,2])
v=np.array([3,2])

  Le produit u\*v est donné par : 

In [23]:
z=u*v
z #c'est une opération element par element avec le meme indice

array([3, 4])

####  Créer ci-dessous le résultat de la multiplication des listes [1,2,3,4,5] et [1,0,1,0,1] :

In [25]:
i=np.array([1,2,3,4,5])#si on ne met pas le np.array cela ne marchera pas
j=np.array([1,0,1,0,1])

k=i*j
k

array([1, 0, 3, 0, 5])

 <div align="right">
<a href="#3" class="btn btn-default" data-toggle="collapse">Solution</a>

</div>
<div id="3" class="collapse">
```
a=np.array([1,2,3,4,5])
b=np.array([1,0,1,0,1])
a*b
```
</div>

#### Dot Product

Le dot product est un produit scalaire lorsqu'il s'agit de deux arrays de dimension 1 :

In [26]:
np.dot(u,v) #il additionne les multiplications entre indices (1*2 + 3*2) cela peut aussi s'écrire 'u.v'

7

### Ajouter une constante à un array numpy  

In [27]:
u=np.array([1,2])
u

array([1, 2])

In [28]:
u+1

array([2, 3])

L'entier 1 a été ajouté à toutes les valeurs de u.

<hr>
Copyright &copy; 2020 Hatem & Driss @NEEDEMAND