<img src = "images/logos.png" width = 600, align = "center">
<br>
<h1 align=center><font size = 5>Numpy 2D </font></h1>

In [1]:
import numpy as np

Soit la liste a contenant 3 listes **de même taille** :

In [2]:
a=[[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

 On peut caster a en un array numpy : 

In [3]:
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Dans ce cas l'attribut **ndim** retourne la dimension : 

In [4]:
A.ndim

2

 L'attribut **shape** retourne la taille de chaque dimension.

In [5]:
A.shape

(3, 3)

La taille totale de A est donnée par l'attribut **size**.

In [6]:
A.size #on preferera le shape au size pour plus de précision

9

### Accès aux valeurs dans un array numpy de dimension > 1 :

Les indices de lectures dans un array à dimension 2 sont similaires à ceux des écritures matricielle  :<br>
Exemple : L'accès à la 3ème valeur de la deuxième liste se fait par :

In [10]:
A[1,2] #la recherche se fait en comptage lignes puis colones en commençant toujours par 0


23

Il est aussi possible d'utiliser la notation suivante :

In [8]:
A[1][2] #on preferera la virgule ex au dessus sous numpy

23

Il est également possible d'effetuer un slicing pour récupérer une partie de l'array. Exemple : Les deux premières colonnes de la première ligne :   

In [11]:
 A[0][0:2] #le 2 n'est pas inclus

array([11, 12])

Ou bien les deux premières lignes de la 3ème colonne:

In [12]:
A[0:2,2]

array([13, 23])

# Operations classiques

Les additions, soustractions et multiplication entre arrays ou multiplications par un scalaire sont similaires aux opérations vues en dimension 1.

 **Multiplication d'Hadamard et Multiplication matricielle ordinaire** :<br>
 Ne pas confondre les opérations A\*B et np.dot(A,B) qui sont des opérations totamlement différentes à usages et contraintes spécifiques :

Considérons les deux arrays numpy suivants : <br>


In [13]:
X= np.array([[1,2],[3,4]])
Y= np.array([[0,3],[1,2]])

In [14]:
X

array([[1, 2],
       [3, 4]])

In [15]:
Y

array([[0, 3],
       [1, 2]])

*Produit d'Hadamard*<br>
Les deux arrays doivent être de même *shape*. Chaque valeur du résultat sera obtenue par la multiplication des valeurs à la même position :

In [16]:
X*Y #produit des 2 position par position

array([[0, 6],
       [3, 8]])

 *Produit matriciel ordinaire*<br>
 Non commutatif, ce produit impose que le nombre de colonnes du 1er membre soit égal au nombre de lignes du second.<br>
 [Un exemple](https://fr.wikipedia.org/wiki/Produit_matriciel#Produit_matriciel_ordinaire)

In [17]:
np.dot(X,Y)#voir l'exemple wikipedia/ regle du produit matriciel : on multiplie lignes par colones

array([[ 2,  7],
       [ 4, 17]])

Ou encore, en modifiant l'array Y :

In [18]:
X= np.array([[1,2],[3,4]])
Y= np.array([[0],[1]])

In [19]:
np.dot(X,Y)

array([[2],
       [4]])

*La transposée* :

In [20]:
X.T #les lignes deviennent des colones les colones deviennent des lignes (je tourne à 90°)

array([[1, 3],
       [2, 4]])

In [22]:
Y.T

array([[0, 1]])

<hr>
Copyright &copy; 2020 Hatem & Driss @NEEDEMAND